module Embulk
  module Input
    module YahooAdsApi
      class Column
        def self.ydn
          [
            {:request_name=>"ACCOUNT_ID", :api_name=>"Account ID"},
            {:request_name=>"ACCOUNT_NAME", :api_name=>"Account Name"},
            {:request_name=>"CAMPAIGN_ID", :api_name=>"Campaign ID"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"Campaign Name"},
            {:request_name=>"ADGROUP_ID", :api_name=>"Ad Group ID"},
            {:request_name=>"ADGROUP_NAME", :api_name=>"Ad Group Name"},
            {:request_name=>"AD_ID", :api_name=>"Ad ID"},
            {:request_name=>"AD_NAME", :api_name=>"Ad Name"},
            {:request_name=>"AD_TYPE", :api_name=>"Ad Type"},
            {:request_name=>"URL_ID", :api_name=>"Destination URL ID"},
            {:request_name=>"URL_NAME", :api_name=>"Destination URL"},
            {:request_name=>"PREF_ID", :api_name=>"Prefecture ID"},
            {:request_name=>"PREF_NAME", :api_name=>"Prefectures"},
            {:request_name=>"CITY_ID", :api_name=>"City ID"},
            {:request_name=>"CITY_NAME", :api_name=>"City"},
            {:request_name=>"WARD_ID", :api_name=>"Ward ID"},
            {:request_name=>"WARD_NAME", :api_name=>"Ward"},
            {:request_name=>"GENDER", :api_name=>"Gender"},
            {:request_name=>"AGE", :api_name=>"Age"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"DAY", :api_name=>"Daily"},
            {:request_name=>"HOUR", :api_name=>"Hourly"},
            {:request_name=>"DELIVER", :api_name=>"Ad Distribution"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"AD_STYLE", :api_name=>"Ad Style (Image Type)"},
            {:request_name=>"MEDIA_ID", :api_name=>"Media ID"},
            {:request_name=>"MEDIA_NAME", :api_name=>"Media Name"},
            {:request_name=>"MEDIA_FILE_NAME", :api_name=>"File Name"},
            {:request_name=>"MEDIA_AD_FORMAT", :api_name=>"Pixel Size"},
            {:request_name=>"AD_TITLE", :api_name=>"Title"},
            {:request_name=>"DESCRIPTION1", :api_name=>"Description 1"},
            {:request_name=>"DESCRIPTION2", :api_name=>"Description 2"},
            {:request_name=>"DISPLAY_URL", :api_name=>"Display URL"},
            {:request_name=>"SEARCHKEYWORD_ID", :api_name=>"Search Keyword ID"},
            {:request_name=>"SEARCHKEYWORD", :api_name=>"Search Keyword"},
            {:request_name=>"CONVERSION_CATEGORY", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CARRIER", :api_name=>"Carrier"},
            {:request_name=>"AD_LAYOUT", :api_name=>"Layout"},
            {:request_name=>"IMAGE_OPTION", :api_name=>"Dynamic Image Extensions"},
            {:request_name=>"CAMPAIGN_LABEL_IDS_JSON", :api_name=>"Campaign label IDs (JSON)"},
            {:request_name=>"CAMPAIGN_LABELS", :api_name=>"Campaign labels"},
            {:request_name=>"CAMPAIGN_LABELS_JSON", :api_name=>"Campaign labels (JSON)"},
            {:request_name=>"ADGROUP_LABEL_IDS_JSON", :api_name=>"Ad group label IDs (JSON)"},
            {:request_name=>"ADGROUP_LABELS", :api_name=>"Ad group labels"},
            {:request_name=>"ADGROUP_LABELS_JSON", :api_name=>"Ad group labels (JSON)"},
            {:request_name=>"AD_LABEL_IDS_JSON", :api_name=>"Ad label IDs (JSON)"},
            {:request_name=>"AD_LABELS", :api_name=>"Ad labels"},
            {:request_name=>"AD_LABELS_JSON", :api_name=>"Ad labels (JSON)"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"OS", :api_name=>"OS"},
            {:request_name=>"APPLI", :api_name=>"Web/App"},
            {:request_name=>"CAMPAIGN_TYPE", :api_name=>"Campaign Type"},
            {:request_name=>"APP_ID", :api_name=>"App ID/Package name"},
            {:request_name=>"APP_NAME", :api_name=>"App Name"},
            {:request_name=>"APP_OS", :api_name=>"App OS"},
            {:request_name=>"CAMPAIGN_GOALS", :api_name=>"Campaign goals"},
            {:request_name=>"CAMPAIGN_BUYING_TYPE", :api_name=>"Campaign buying type"},
            {:request_name=>"DESTINATION_URL_CAMPAIGN_BANNER", :api_name=>"Destination URL (campaign banner)"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"CLICK", :api_name=>"Clicks"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"AVG_DELIVER_RANK", :api_name=>"Avg. position"},
            {:request_name=>"TOTAL_VIEWABLE_IMPS", :api_name=>"Measured impressions (previous)"},
            {:request_name=>"VIEWABLE_IMPS", :api_name=>"Viewable impressions"},
            {:request_name=>"INVIEW_RATE", :api_name=>"Viewable impression rate (previous)"},
            {:request_name=>"INVIEW_CLICK", :api_name=>"Viewable clicks (previous)"},
            {:request_name=>"INVIEW_CLICK_RATE", :api_name=>"Viewable CTR (previous)"},
            {:request_name=>"AVG_CPV", :api_name=>"Avg. CPV"},
            {:request_name=>"VIDEO_VIEWS_TO_25", :api_name=>"25% video views"},
            {:request_name=>"VIDEO_VIEWS_TO_50", :api_name=>"50% video views"},
            {:request_name=>"VIDEO_VIEWS_TO_75", :api_name=>"75% video views"},
            {:request_name=>"VIDEO_VIEWS_TO_95", :api_name=>"95% video views"},
            {:request_name=>"VIDEO_VIEWS_TO_100", :api_name=>"100% video views"},
            {:request_name=>"AVG_PERCENT_VIDEO_VIEWED", :api_name=>"Avg. video view rate"},
            {:request_name=>"AVG_DURATION_VIDEO_VIEWED", :api_name=>"Avg. duration of video viewed"},
            {:request_name=>"VIDEO_VIEWS", :api_name=>"Video views"},
            {:request_name=>"PAID_VIDEO_VIEWS", :api_name=>"Paid video views (CPV)"},
            {:request_name=>"PAID_VIDEO_VIEW_RATE", :api_name=>"Paid video view rate (CPV)"},
            {:request_name=>"VIDEO_VIEWS_TO_3_SEC", :api_name=>"3 sec video views"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. rate"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost/conv."},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. value"},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Conv. value/conv."},
            {:request_name=>"ALL_CONV", :api_name=>"Conversions (all)"},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"Conv. rate (all)"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost/conv. (all)"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"Conv. value (all)"},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Conv. value (all)/conv. (all)"},
            {:request_name=>"CONVERSIONS_VIA_AD_CLICK", :api_name=>"Conversions (via click)"},
            {:request_name=>"CONVERSION_RATE_VIA_AD_CLICK", :api_name=>"Conv. rate (via click)"},
            {:request_name=>"COST_PER_CONV_VIA_AD_CLICK", :api_name=>"Cost/conv. (via click)"},
            {:request_name=>"CONV_VALUE_VIA_AD_CLICK", :api_name=>"Conv. value (via click)"},
            {:request_name=>"VALUE_PER_CONV_VIA_AD_CLICK", :api_name=>"Conv. value (via click)/conv. (via click)"},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Cross-device conv."},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. value/cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"Conv. value (all)/cost"},
            {:request_name=>"CONV_VALUE_VIA_AD_CLICK_PER_COST", :api_name=>"Conv. value (via click)/cost"},
            {:request_name=>"IMPS_PREV", :api_name=>"Impressions (previous)"},
            {:request_name=>"CLICK_RATE_PREV", :api_name=>"CTR (previous)"},
            {:request_name=>"AVG_CPM", :api_name=>"Avg. CPM"},
            {:request_name=>"AVG_VCPM", :api_name=>"Avg. vCPM"},
            {:request_name=>"MEASURED_IMPS", :api_name=>"Measured impressions"},
            {:request_name=>"VIEWABLE_CLICK", :api_name=>"Viewable clicks"},
            {:request_name=>"MEASURED_IMPS_RATE", :api_name=>"Measured impression rate"},
            {:request_name=>"VIEWABLE_IMPS_RATE", :api_name=>"Viewable impression rate"},
            {:request_name=>"VIEWABLE_CLICK_RATE", :api_name=>"Viewable CTR"},
            {:request_name=>"VIDEO_VIEWS_TO_10_SEC", :api_name=>"10 sec video views"},
          ]
        end
        def self.account
          [
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICKS", :api_name=>"Clicks"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"INVALID_CLICKS", :api_name=>"Invalid Clicks"},
            {:request_name=>"INVALID_CLICK_RATE", :api_name=>"Invalid Click Rate"},
            {:request_name=>"IMPRESSION_SHARE", :api_name=>"Impression Share"},
            {:request_name=>"EXACT_MATCH_IMPRESSION_SHARE", :api_name=>"Exact Match Impression Share"},
            {:request_name=>"BUDGET_LOST_IMPRESSION_SHARE", :api_name=>"Budget Lost Impression Share"},
            {:request_name=>"QUALITY_LOST_IMPRESSION_SHARE", :api_name=>"Quality Lost Impression Share"},
            {:request_name=>"TRACKING_URL", :api_name=>"Tracking URL"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. Rate"},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. Value"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost Per Conv."},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Value Per Conv."},
            {:request_name=>"ALL_CONV", :api_name=>"All Conv."},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"All Conv. Rate"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"All Conv. Value"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost Per All Conv."},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Value Per All Conv."},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Conversions across devices"},
            {:request_name=>"NETWORK", :api_name=>"Network"},
            {:request_name=>"CLICK_TYPE", :api_name=>"ClickType"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"DAY", :api_name=>"Day"},
            {:request_name=>"DAY_OF_WEEK", :api_name=>"Day of week"},
            {:request_name=>"QUARTER", :api_name=>"Quarter"},
            {:request_name=>"YEAR", :api_name=>"Year"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"MONTH_OF_YEAR", :api_name=>"Month of Year"},
            {:request_name=>"WEEK", :api_name=>"Week"},
            {:request_name=>"HOUR_OF_DAY", :api_name=>"Hour of day"},
            {:request_name=>"OBJECT_OF_CONVERSION_TRACKING", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. Value Per Cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"All Conv. Value Per Cost"},
          ]
        end
        def self.campaign
          [
            {:request_name=>"CAMPAIGN_ID", :api_name=>"CampaignID"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"Campaign Name"},
            {:request_name=>"CAMPAIGN_DISTRIBUTION_SETTINGS", :api_name=>"Distribution Settings"},
            {:request_name=>"CAMPAIGN_DISTRIBUTION_STATUS", :api_name=>"Distribution Status"},
            {:request_name=>"DAILY_SPENDING_LIMIT", :api_name=>"Daily Spending Limit"},
            {:request_name=>"CAMPAIGN_START_DATE", :api_name=>"Start Date"},
            {:request_name=>"CAMPAIGN_END_DATE", :api_name=>"End Date"},
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICKS", :api_name=>"Clicks"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"INVALID_CLICKS", :api_name=>"Invalid Clicks"},
            {:request_name=>"INVALID_CLICK_RATE", :api_name=>"Invalid Click Rate"},
            {:request_name=>"IMPRESSION_SHARE", :api_name=>"Impression Share"},
            {:request_name=>"EXACT_MATCH_IMPRESSION_SHARE", :api_name=>"Exact Match Impression Share"},
            {:request_name=>"BUDGET_LOST_IMPRESSION_SHARE", :api_name=>"Budget Lost Impression Share"},
            {:request_name=>"QUALITY_LOST_IMPRESSION_SHARE", :api_name=>"Quality Lost Impression Share"},
            {:request_name=>"TRACKING_URL", :api_name=>"Tracking URL"},
            {:request_name=>"CUSTOM_PARAMETERS", :api_name=>"Custom Parameters"},
            {:request_name=>"CAMPAIGN_TRACKING_ID", :api_name=>"Campaign Tracking ID"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. Rate"},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. Value"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost Per Conv."},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Value Per Conv."},
            {:request_name=>"ALL_CONV", :api_name=>"All Conv."},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"All Conv. Rate"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"All Conv. Value"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost Per All Conv."},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Value Per All Conv."},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Conversions across devices"},
            {:request_name=>"CAMPAIGN_MOBILE_BID_MODIFIER", :api_name=>"Smartphone Bid Adjustment (%)"},
            {:request_name=>"CAMPAIGN_DESKTOP_BID_MODIFIER", :api_name=>"PC Bid Adjustment (%)"},
            {:request_name=>"CAMPAIGN_TABLET_BID_MODIFIER", :api_name=>"Tablet Bid Adjustment (%)"},
            {:request_name=>"NETWORK", :api_name=>"Network"},
            {:request_name=>"CLICK_TYPE", :api_name=>"ClickType"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"DAY", :api_name=>"Day"},
            {:request_name=>"DAY_OF_WEEK", :api_name=>"Day of week"},
            {:request_name=>"QUARTER", :api_name=>"Quarter"},
            {:request_name=>"YEAR", :api_name=>"Year"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"MONTH_OF_YEAR", :api_name=>"Month of Year"},
            {:request_name=>"WEEK", :api_name=>"Week"},
            {:request_name=>"HOUR_OF_DAY", :api_name=>"Hour of day"},
            {:request_name=>"OBJECT_OF_CONVERSION_TRACKING", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"CAMPAIGN_TYPE", :api_name=>"Campaign type"},
            {:request_name=>"LABELS", :api_name=>"Labels"},
            {:request_name=>"LABELS_JSON", :api_name=>"Labels(JSON)"},
            {:request_name=>"BID_STRATEGY_ID", :api_name=>"Auto Bidding ID"},
            {:request_name=>"BID_STRATEGY_NAME", :api_name=>"Auto Bidding Name"},
            {:request_name=>"BID_STRATEGY_TYPE", :api_name=>"Bidding"},
            {:request_name=>"ENHANCED_CPC_ENABLED", :api_name=>"Enhanced CPC"},
            {:request_name=>"ABSOLUTE_TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search absolute top impression rate"},
            {:request_name=>"TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search top impression rate"},
            {:request_name=>"SEARCH_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search absolute top impression share"},
            {:request_name=>"SEARCH_TOP_IMPRESSION_SHARE", :api_name=>"Search top impression share"},
            {:request_name=>"SEARCH_BUDGET_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (rank)"},
            {:request_name=>"SEARCH_BUDGET_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (rank)"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. Value Per Cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"All Conv. Value Per Cost"},
          ]
        end
        def self.adgroup
          [
            {:request_name=>"CAMPAIGN_ID", :api_name=>"CampaignID"},
            {:request_name=>"ADGROUP_ID", :api_name=>"Ad Group ID"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"Campaign Name"},
            {:request_name=>"ADGROUP_NAME", :api_name=>"Ad Group Name"},
            {:request_name=>"ADGROUP_DISTRIBUTION_SETTINGS", :api_name=>"Distribution Settings"},
            {:request_name=>"ADGROUP_BID", :api_name=>"Ad Group Bid"},
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICKS", :api_name=>"Clicks"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"IMPRESSION_SHARE", :api_name=>"Impression Share"},
            {:request_name=>"EXACT_MATCH_IMPRESSION_SHARE", :api_name=>"Exact Match Impression Share"},
            {:request_name=>"QUALITY_LOST_IMPRESSION_SHARE", :api_name=>"Quality Lost Impression Share"},
            {:request_name=>"TRACKING_URL", :api_name=>"Tracking URL"},
            {:request_name=>"CUSTOM_PARAMETERS", :api_name=>"Custom Parameters"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. Rate"},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. Value"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost Per Conv."},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Value Per Conv."},
            {:request_name=>"ALL_CONV", :api_name=>"All Conv."},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"All Conv. Rate"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"All Conv. Value"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost Per All Conv."},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Value Per All Conv."},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Conversions across devices"},
            {:request_name=>"ADGROUP_MOBILE_BID_MODIFIER", :api_name=>"Smartphone Bid Adjustment (%)"},
            {:request_name=>"ADGROUP_DESKTOP_BID_MODIFIER", :api_name=>"PC Bid Adjustment (%)"},
            {:request_name=>"ADGROUP_TABLET_BID_MODIFIER", :api_name=>"Tablet Bid Adjustment (%)"},
            {:request_name=>"CAMPAIGN_TRACKING_ID", :api_name=>"Campaign Tracking ID"},
            {:request_name=>"ADGROUP_TRACKING_ID", :api_name=>"Ad Group Tracking ID"},
            {:request_name=>"NETWORK", :api_name=>"Network"},
            {:request_name=>"CLICK_TYPE", :api_name=>"ClickType"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"DAY", :api_name=>"Day"},
            {:request_name=>"DAY_OF_WEEK", :api_name=>"Day of week"},
            {:request_name=>"QUARTER", :api_name=>"Quarter"},
            {:request_name=>"YEAR", :api_name=>"Year"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"MONTH_OF_YEAR", :api_name=>"Month of Year"},
            {:request_name=>"WEEK", :api_name=>"Week"},
            {:request_name=>"HOUR_OF_DAY", :api_name=>"Hour of day"},
            {:request_name=>"OBJECT_OF_CONVERSION_TRACKING", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"LABELS", :api_name=>"Labels"},
            {:request_name=>"LABELS_JSON", :api_name=>"Labels(JSON)"},
            {:request_name=>"ABSOLUTE_TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search absolute top impression rate"},
            {:request_name=>"TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search top impression rate"},
            {:request_name=>"SEARCH_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search absolute top impression share"},
            {:request_name=>"SEARCH_TOP_IMPRESSION_SHARE", :api_name=>"Search top impression share"},
            {:request_name=>"SEARCH_BUDGET_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (rank)"},
            {:request_name=>"SEARCH_BUDGET_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (rank)"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. Value Per Cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"All Conv. Value Per Cost"},
          ]
        end
        def self.ad
          [
            {:request_name=>"CAMPAIGN_ID", :api_name=>"CampaignID"},
            {:request_name=>"ADGROUP_ID", :api_name=>"Ad Group ID"},
            {:request_name=>"AD_ID", :api_name=>"Ad ID"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"Campaign Name"},
            {:request_name=>"ADGROUP_NAME", :api_name=>"Ad Group Name"},
            {:request_name=>"AD_NAME", :api_name=>"Ad Name"},
            {:request_name=>"TITLE", :api_name=>"Title"},
            {:request_name=>"DESCRIPTION", :api_name=>"Description 1"},
            {:request_name=>"DISPLAY_URL", :api_name=>"Display URL"},
            {:request_name=>"DESTINATION_URL", :api_name=>"Destination URL"},
            {:request_name=>"AD_TYPE", :api_name=>"Ad Type"},
            {:request_name=>"AD_DISTRIBUTION_SETTINGS", :api_name=>"Distribution Settings"},
            {:request_name=>"AD_EDITORIAL_STATUS", :api_name=>"Editorial Status"},
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICKS", :api_name=>"Clicks"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"DESCRIPTION2", :api_name=>"Description 2"},
            {:request_name=>"DEVICE_PREFERENCE", :api_name=>"Focus Device"},
            {:request_name=>"TRACKING_URL", :api_name=>"Tracking URL"},
            {:request_name=>"CUSTOM_PARAMETERS", :api_name=>"Custom Parameters"},
            {:request_name=>"LANDING_PAGE_URL", :api_name=>"Landing Page URL"},
            {:request_name=>"LANDING_PAGE_URL_SMARTPHONE", :api_name=>"Landing Page URL (Smartphone)"},
            {:request_name=>"CAMPAIGN_TRACKING_ID", :api_name=>"Campaign Tracking ID"},
            {:request_name=>"AD_TRACKING_ID", :api_name=>"Ad Tracking ID"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. Rate"},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. Value"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost Per Conv."},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Value Per Conv."},
            {:request_name=>"ALL_CONV", :api_name=>"All Conv."},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"All Conv. Rate"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"All Conv. Value"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost Per All Conv."},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Value Per All Conv."},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Conversions across devices"},
            {:request_name=>"ADGROUP_TRACKING_ID", :api_name=>"Ad Group Tracking ID"},
            {:request_name=>"NETWORK", :api_name=>"Network"},
            {:request_name=>"CLICK_TYPE", :api_name=>"ClickType"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"DAY", :api_name=>"Day"},
            {:request_name=>"DAY_OF_WEEK", :api_name=>"Day of week"},
            {:request_name=>"QUARTER", :api_name=>"Quarter"},
            {:request_name=>"YEAR", :api_name=>"Year"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"MONTH_OF_YEAR", :api_name=>"Month of Year"},
            {:request_name=>"WEEK", :api_name=>"Week"},
            {:request_name=>"OBJECT_OF_CONVERSION_TRACKING", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"AD_KEYWORD_ID", :api_name=>"Keyword ID"},
            {:request_name=>"TITLE1", :api_name=>"Title1"},
            {:request_name=>"TITLE2", :api_name=>"Title2"},
            {:request_name=>"DESC", :api_name=>"Description"},
            {:request_name=>"DIRECTORY1", :api_name=>"Directory1"},
            {:request_name=>"DIRECTORY2", :api_name=>"Directory2"},
            {:request_name=>"LABELS", :api_name=>"Labels"},
            {:request_name=>"LABELS_JSON", :api_name=>"Labels(JSON)"},
            {:request_name=>"ABSOLUTE_TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search absolute top impression rate"},
            {:request_name=>"TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search top impression rate"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. Value Per Cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"All Conv. Value Per Cost"},
          ]
        end
        def self.keywords
          [
            {:request_name=>"CAMPAIGN_ID", :api_name=>"CampaignID"},
            {:request_name=>"ADGROUP_ID", :api_name=>"Ad Group ID"},
            {:request_name=>"KEYWORD_ID", :api_name=>"Keyword ID"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"Campaign Name"},
            {:request_name=>"ADGROUP_NAME", :api_name=>"Ad Group Name"},
            {:request_name=>"CUSTOM_URL", :api_name=>"Custom URL"},
            {:request_name=>"KEYWORD", :api_name=>"Keyword"},
            {:request_name=>"KEYWORD_DISTRIBUTION_SETTINGS", :api_name=>"Distribution Settings"},
            {:request_name=>"KEYWORD_EDITORIAL_STATUS", :api_name=>"Editorial Status"},
            {:request_name=>"ADGROUP_BID", :api_name=>"Ad Group Bid"},
            {:request_name=>"BID", :api_name=>"Bid (JPY)"},
            {:request_name=>"NEGATIVE_KEYWORD", :api_name=>"Negative Keywords"},
            {:request_name=>"QUALITY_INDEX", :api_name=>"Quality Index"},
            {:request_name=>"FIRST_PAGE_BID_ESTIMATE", :api_name=>"First Page Bid Estimate"},
            {:request_name=>"KEYWORD_MATCH_TYPE", :api_name=>"Match Type"},
            {:request_name=>"COST", :api_name=>"Cost"},
            {:request_name=>"IMPS", :api_name=>"Impressions"},
            {:request_name=>"CLICKS", :api_name=>"Clicks"},
            {:request_name=>"CLICK_RATE", :api_name=>"CTR"},
            {:request_name=>"AVG_CPC", :api_name=>"Avg. CPC"},
            {:request_name=>"IMPRESSION_SHARE", :api_name=>"Impression Share"},
            {:request_name=>"EXACT_MATCH_IMPRESSION_SHARE", :api_name=>"Exact Match Impression Share"},
            {:request_name=>"QUALITY_LOST_IMPRESSION_SHARE", :api_name=>"Quality Lost Impression Share"},
            {:request_name=>"TOP_OF_PAGE_BID_ESTIMATE", :api_name=>"Top Of Page Bid Estimate"},
            {:request_name=>"TRACKING_URL", :api_name=>"Tracking URL"},
            {:request_name=>"CUSTOM_PARAMETERS", :api_name=>"Custom Parameters"},
            {:request_name=>"LANDING_PAGE_URL", :api_name=>"Landing Page URL"},
            {:request_name=>"LANDING_PAGE_URL_SMARTPHONE", :api_name=>"Landing Page URL (Smartphone)"},
            {:request_name=>"CONVERSIONS", :api_name=>"Conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"Conv. Rate"},
            {:request_name=>"CONV_VALUE", :api_name=>"Conv. Value"},
            {:request_name=>"COST_PER_CONV", :api_name=>"Cost Per Conv."},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"Value Per Conv."},
            {:request_name=>"ALL_CONV", :api_name=>"All Conv."},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"All Conv. Rate"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"All Conv. Value"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"Cost Per All Conv."},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"Value Per All Conv."},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"Conversions across devices"},
            {:request_name=>"CAMPAIGN_TRACKING_ID", :api_name=>"Campaign Tracking ID"},
            {:request_name=>"ADGROUP_TRACKING_ID", :api_name=>"Ad Group Tracking ID"},
            {:request_name=>"KEYWORD_TRACKING_ID", :api_name=>"Keyword Tracking ID"},
            {:request_name=>"NETWORK", :api_name=>"Network"},
            {:request_name=>"CLICK_TYPE", :api_name=>"ClickType"},
            {:request_name=>"DEVICE", :api_name=>"Device"},
            {:request_name=>"DAY", :api_name=>"Day"},
            {:request_name=>"DAY_OF_WEEK", :api_name=>"Day of week"},
            {:request_name=>"QUARTER", :api_name=>"Quarter"},
            {:request_name=>"YEAR", :api_name=>"Year"},
            {:request_name=>"MONTH", :api_name=>"Month"},
            {:request_name=>"MONTH_OF_YEAR", :api_name=>"Month of Year"},
            {:request_name=>"WEEK", :api_name=>"Week"},
            {:request_name=>"OBJECT_OF_CONVERSION_TRACKING", :api_name=>"Objective of Conversion Tracking"},
            {:request_name=>"CONVERSION_NAME", :api_name=>"Conversion Name"},
            {:request_name=>"LABELS", :api_name=>"Labels"},
            {:request_name=>"LABELS_JSON", :api_name=>"Labels(JSON)"},
            {:request_name=>"ABSOLUTE_TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search absolute top impression rate"},
            {:request_name=>"TOP_IMPRESSION_PERCENTAGE", :api_name=>"Search top impression rate"},
            {:request_name=>"SEARCH_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search absolute top impression share"},
            {:request_name=>"SEARCH_TOP_IMPRESSION_SHARE", :api_name=>"Search top impression share"},
            {:request_name=>"SEARCH_BUDGET_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE", :api_name=>"Search lost absolute top impression share (rank)"},
            {:request_name=>"SEARCH_BUDGET_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (budget)"},
            {:request_name=>"SEARCH_RANK_LOST_TOP_IMPRESSION_SHARE", :api_name=>"Search lost top impression share (rank)"},
            {:request_name=>"SYSTEM_SERVING_STATUS", :api_name=>"Keyword status"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"Conv. Value Per Cost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"All Conv. Value Per Cost"},
          ]
        end
        def self.stats
          [
            {:request_name=>"CAMPAIGN_ID", :api_name=>"campaignId"},
            {:request_name=>"CAMPAIGN_NAME", :api_name=>"campaignName"},
            {:request_name=>"ADGROUP_ID", :api_name=>"adGroupId"},
            {:request_name=>"ADGROUP_NAME", :api_name=>"adGroupName"},
            {:request_name=>"AD_ID", :api_name=>"adId"},
            {:request_name=>"AD_NAME", :api_name=>"adName"},
            {:request_name=>"IMPS", :api_name=>"imps"},
            {:request_name=>"IMPS_PREV", :api_name=>"impsPrev"},
            {:request_name=>"CLICK", :api_name=>"clickCnt"},
            {:request_name=>"CLICK_RATE", :api_name=>"clickRate"},
            {:request_name=>"CLICK_RATE_PREV", :api_name=>"clickRatePrev"},
            {:request_name=>"COST", :api_name=>"cost"},
            {:request_name=>"AVG_CPC", :api_name=>"avgCpc"},
            {:request_name=>"CONVERSIONS", :api_name=>"conversions"},
            {:request_name=>"CONV_RATE", :api_name=>"conversionRate"},
            {:request_name=>"CONVERSIONS_VIA_AD_CLICK", :api_name=>"conversionsViaAdClick"},
            {:request_name=>"CONVERSION_RATE_VIA_AD_CLICK", :api_name=>"conversionRateViaAdClick"},
            {:request_name=>"ALL_CONV", :api_name=>"allConversions"},
            {:request_name=>"ALL_CONV_RATE", :api_name=>"allConversionRate"},
            {:request_name=>"COST_PER_CONV", :api_name=>"cpa"},
            {:request_name=>"CONV_VALUE", :api_name=>"conversionValue"},
            {:request_name=>"VALUE_PER_CONV", :api_name=>"valuePerConversions"},
            {:request_name=>"CONV_VALUE_PER_COST", :api_name=>"convValuePerCost"},
            {:request_name=>"ALL_CONV_VALUE_PER_COST", :api_name=>"allConvValuePerCost"},
            {:request_name=>"CONV_VALUE_VIA_AD_CLICK_PER_COST", :api_name=>"convValueViaAdClickPerCost"},
            {:request_name=>"ALL_CONV_VALUE", :api_name=>"allConversionValue"},
            {:request_name=>"VALUE_PER_ALL_CONV", :api_name=>"valuePerAllConversions"},
            {:request_name=>"CONV_VALUE_VIA_AD_CLICK", :api_name=>"conversionValueViaAdClick"},
            {:request_name=>"VALUE_PER_CONV_VIA_AD_CLICK", :api_name=>"valuePerConversionsViaAdClick"},
            {:request_name=>"COST_PER_CONV_VIA_AD_CLICK", :api_name=>"cpaViaAdClick"},
            {:request_name=>"COST_PER_ALL_CONV", :api_name=>"allCpa"},
            {:request_name=>"CROSS_DEVICE_CONVERSIONS", :api_name=>"crossDeviceConversions"},
            {:request_name=>"AVG_DELIVER_RANK", :api_name=>"avgDeliverRank"},
            {:request_name=>"MEASURED_IMPS", :api_name=>"measuredImps"},
            {:request_name=>"TOTAL_VIEWABLE_IMPS", :api_name=>"totalVimps"},
            {:request_name=>"MEASURED_IMPS_RATE", :api_name=>"measuredImpsRate"},
            {:request_name=>"VIEWABLE_IMPS", :api_name=>"vimps"},
            {:request_name=>"VIEWABLE_IMPS_RATE", :api_name=>"viewableImpsRate"},
            {:request_name=>"INVIEW_RATE", :api_name=>"inViewRate"},
            {:request_name=>"VIEWABLE_CLICK", :api_name=>"viewableClicks"},
            {:request_name=>"INVIEW_CLICK", :api_name=>"inViewClickCnt"},
            {:request_name=>"VIEWABLE_CLICK_RATE", :api_name=>"viewableClickRate"},
            {:request_name=>"INVIEW_CLICK_RATE", :api_name=>"inViewClickRate"},
            {:request_name=>"PAID_VIDEO_VIEWS", :api_name=>"paidVideoViews"},
            {:request_name=>"PAID_VIDEO_VIEW_RATE", :api_name=>"paidVideoViewRate"},
            {:request_name=>"AVG_CPV", :api_name=>"averageCpv"},
            {:request_name=>"VIDEO_VIEWS", :api_name=>"videoViews"},
            {:request_name=>"VIDEO_VIEWS_TO_25", :api_name=>"videoViewsTo25"},
            {:request_name=>"VIDEO_VIEWS_TO_50", :api_name=>"videoViewsTo50"},
            {:request_name=>"VIDEO_VIEWS_TO_75", :api_name=>"videoViewsTo75"},
            {:request_name=>"VIDEO_VIEWS_TO_95", :api_name=>"videoViewsTo95"},
            {:request_name=>"VIDEO_VIEWS_TO_100", :api_name=>"videoViewsTo100"},
            {:request_name=>"VIDEO_VIEWS_TO_3_SEC", :api_name=>"videoViewsTo3Sec"},
            {:request_name=>"VIDEO_VIEWS_TO_10_SEC", :api_name=>"videoViewsTo10Sec"},
            {:request_name=>"AVG_PERCENT_VIDEO_VIEWED", :api_name=>"averageRateVideoViewed"},
            {:request_name=>"AVG_DURATION_VIDEO_VIEWED", :api_name=>"averageDurationVideoViewed"},
          ]
        end
      end
    end
  end
end
